steps:
  - id: "test"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'TARGETPLATFORM=linux/amd64'
      - '.'

options:
  logging: CLOUD_LOGGING_ONLY
